# Generated by Django 4.0.2 on 2022-02-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='some_text',
            field=models.TextField(default='Default text'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.CharField(default='My vendor', max_length=255),
        ),
    ]
