# Generated by Django 4.0.2 on 2022-02-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0002_transaction_price_transaction_some_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='boolean_field1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='boolean_field2',
            field=models.BooleanField(default=True),
        ),
    ]
